# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'Independent Study App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Independent Study App

  pod 'LBTAComponents', '~> 1.0.2'

end
